// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by typegen at 2026-01-28T03:13:05-06:00
// Run 'make typegen' in the backend directory to regenerate

// ============================================================================
// Base Response Types
// ============================================================================

/** Standard API response wrapper */
export interface APIResponse<T> {
  data?: T;
  error?: string;
}

/** Paginated response wrapper */
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
  has_more: boolean;
}

/** Simple success response */
export interface SuccessResponse {
  success: boolean;
  message?: string;
}

/** Error response */
export interface ErrorResponse {
  error: string;
  code?: string;
  details?: string;
}

// ============================================================================
// Auth Types
// ============================================================================

/** User data transfer object */
export interface UserDTO {
  id: string;
  email: string;
  created_at: string;
}

/** Authentication response with tokens */
export interface AuthResponse {
  access_token: string;
  refresh_token: string;
  expires_at: string;
  user: UserDTO;
}

/** Registration request */
export interface RegisterRequest {
  email: string;
  password: string;
}

/** Login request */
export interface LoginRequest {
  email: string;
  password: string;
}

/** Token refresh request */
export interface RefreshRequest {
  refresh_token: string;
}

// ============================================================================
// Conversation Types
// ============================================================================

/** Conversation data transfer object */
export interface ConversationDTO {
  id: string;
  title: string;
  provider: string;
  model: string;
  system_prompt?: string;
  created_at: string;
  updated_at: string;
}

/** Message data transfer object */
export interface MessageDTO {
  id: string;
  role: string;
  content: string;
  tool_calls?: Record<string, unknown>[];
  tool_call_id?: string;
  created_at: string;
}

/** Create conversation request */
export interface CreateConversationRequest {
  provider: string;
  model: string;
  system_prompt?: string;
}

/** Update conversation request */
export interface UpdateConversationRequest {
  title: string;
}

/** Conversation list response */
export interface ConversationListResponse {
  conversations: ConversationDTO[];
}

/** Message list response */
export interface MessageListResponse {
  messages: MessageDTO[];
}

// ============================================================================
// Provider Types
// ============================================================================

/** Set API key request */
export interface SetKeyRequest {
  api_key: string;
}

/** Validate API key request */
export interface ValidateKeyRequest {
  api_key: string;
}

/** Key status response */
export interface KeyStatusResponse {
  has_key: boolean;
  provider: string;
}

/** Key validation response */
export interface KeyValidationResponse {
  valid: boolean;
  message?: string;
}

/** Provider list response */
export interface ProviderListResponse {
  providers: string[];
}

// ============================================================================
// Workspace Types
// ============================================================================

/** Directory response */
export interface DirectoryResponse {
  path: string;
}

/** Set directory request */
export interface SetDirectoryRequest {
  directory: string;
}

/** Browse directory entry */
export interface BrowseDirectoryEntry {
  name: string;
  path: string;
}

/** Browse directories response */
export interface BrowseDirectoriesResponse {
  current_path: string;
  parent_path: string;
  directories: BrowseDirectoryEntry[];
}

/** Workspace info */
export interface WorkspaceInfo {
  id: string;
  path: string;
  name: string;
  is_current: boolean;
  last_accessed_at?: string;
}

/** Workspace list response */
export interface WorkspaceListResponse {
  workspaces: WorkspaceInfo[];
}

/** Clone repository request */
export interface CloneRepoRequest {
  repo_url: string;
  branch?: string;
}

/** Clone repository response */
export interface CloneRepoResponse {
  success: boolean;
  path: string;
  message: string;
}

// ============================================================================
// File Types
// ============================================================================

/** File node in the file tree */
export interface FileNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: FileNode[];
}

/** File list response */
export interface FileListResponse {
  files: FileNode[];
}

/** File content response */
export interface FileContentResponse {
  path: string;
  content: string;
}

/** Write file request */
export interface WriteFileRequest {
  path: string;
  content: string;
}

/** Rename file request */
export interface RenameFileRequest {
  source_path: string;
  dest_path: string;
}

/** Create directory request */
export interface CreateDirectoryRequest {
  path: string;
}

// ============================================================================
// Integration Types
// ============================================================================

/** Integration status */
export interface IntegrationStatus {
  enabled: boolean;
  connected: boolean;
  channel_id?: string;
}

/** Integration status response */
export interface IntegrationStatusResponse {
  discord: IntegrationStatus;
  slack: IntegrationStatus;
  posthog: IntegrationStatus;
}

/** Set integration request */
export interface SetIntegrationRequest {
  webhook_url?: string;
  channel_id?: string;
  enabled: boolean;
}

// ============================================================================
// Build Types
// ============================================================================

/** Build status */
export type BuildStatus = 'pending' | 'running' | 'success' | 'failed';

/** Build info */
export interface BuildInfo {
  id: string;
  status: BuildStatus;
  command: string;
  start_time: string;
  end_time?: string;
  duration_ms?: number;
  error?: string;
  preview_url?: string;
}

// ============================================================================
// GitHub Types
// ============================================================================

/** GitHub connection status */
export interface GitHubStatusResponse {
  connected: boolean;
  username?: string;
  avatar_url?: string;
}

/** GitHub repository info */
export interface GitHubRepoInfo {
  id: number;
  name: string;
  full_name: string;
  description?: string;
  private: boolean;
  html_url: string;
  clone_url: string;
  default_branch: string;
}

/** GitHub repos response */
export interface GitHubReposResponse {
  repos: GitHubRepoInfo[];
}

// ============================================================================
// API Endpoint Paths
// ============================================================================

/** All API endpoint paths */
export const API_PATHS = {
  // Auth
  AUTH_REGISTER: '/api/v1/auth/register',
  AUTH_LOGIN: '/api/v1/auth/login',
  AUTH_LOGOUT: '/api/v1/auth/logout',
  AUTH_REFRESH: '/api/v1/auth/refresh',
  AUTH_ME: '/api/v1/auth/me',
  AUTH_GUEST: '/api/v1/auth/guest',

  // Conversations
  CONVERSATIONS_LIST: '/api/v1/conversations',
  CONVERSATIONS_SEARCH: '/api/v1/conversations/search',
  CONVERSATIONS_CREATE: '/api/v1/conversations',
  CONVERSATION_GET: (id: string) => `/api/v1/conversations/${id}`,
  CONVERSATION_UPDATE: (id: string) => `/api/v1/conversations/${id}`,
  CONVERSATION_DELETE: (id: string) => `/api/v1/conversations/${id}`,
  CONVERSATION_MESSAGES: (id: string) => `/api/v1/conversations/${id}/messages`,

  // Providers
  PROVIDERS_LIST: '/api/v1/providers',
  PROVIDER_SET_KEY: (provider: string) => `/api/v1/providers/${provider}/key`,
  PROVIDER_DELETE_KEY: (provider: string) => `/api/v1/providers/${provider}/key`,
  PROVIDER_VALIDATE_KEY: (provider: string) => `/api/v1/providers/${provider}/validate`,
  PROVIDER_KEY_STATUS: (provider: string) => `/api/v1/providers/${provider}/status`,
  PROVIDERS_KEYS: '/api/v1/providers/keys',

  // Workspace
  WORKSPACE_DIRECTORY: '/api/v1/workspace/directory',
  WORKSPACE_BROWSE: '/api/v1/workspace/browse',
  WORKSPACE_PICK_FOLDER: '/api/v1/workspace/pick-folder',
  WORKSPACE_RECENT: '/api/v1/workspace/recent',
  WORKSPACE_REMOVE: (id: string) => `/api/v1/workspace/${id}`,
  WORKSPACE_SET_CURRENT: (id: string) => `/api/v1/workspace/${id}/current`,

  // Sandbox/Files
  SANDBOX_FILES: '/api/v1/sandbox/files',
  SANDBOX_FILE: (path: string) => `/api/v1/sandbox/files/${path}`,

  // Builds
  BUILD_GET: (id: string) => `/api/v1/sandbox/builds/${id}`,
  BUILD_STOP: (id: string) => `/api/v1/sandbox/builds/${id}/stop`,

  // GitHub
  GITHUB_STATUS: '/api/v1/github/status',
  GITHUB_REPOS: '/api/v1/github/repos',
  GITHUB_CLONE: '/api/v1/github/clone',
  GITHUB_DISCONNECT: '/api/v1/github/disconnect',
  OAUTH_GITHUB_AUTHORIZE: '/api/v1/oauth/github/authorize',

  // Integrations
  INTEGRATIONS_STATUS: '/api/v1/integrations',
  INTEGRATIONS_DISCORD: '/api/v1/integrations/discord',
  INTEGRATIONS_SLACK: '/api/v1/integrations/slack',
  INTEGRATIONS_POSTHOG: '/api/v1/integrations/posthog',

  // WebSocket
  WEBSOCKET: '/api/v1/ws',

  // Agents
  AGENTS_LIST: '/api/v1/agents',
  AGENT_GET: (id: string) => `/api/v1/agents/${id}`,
  AGENT_DELETE: (id: string) => `/api/v1/agents/${id}`,
  AGENT_RESULTS: (id: string) => `/api/v1/agents/${id}/results`,
  AGENTS_BY_CONVERSATION: (conversationId: string) => `/api/v1/conversations/${conversationId}/agents`,

  // Tasks
  TASKS_LIST: '/api/v1/tasks',
  TASK_GET: (id: string) => `/api/v1/tasks/${id}`,
  TASK_CANCEL: (id: string) => `/api/v1/tasks/${id}`,
  TASK_RETRY: (id: string) => `/api/v1/tasks/${id}/retry`,
  TASKS_STATS: '/api/v1/tasks/stats',
} as const;

// ============================================================================
// WebSocket Message Types
// ============================================================================

/** WebSocket message types */
export type WSMessageType =
  | 'chat.message'
  | 'chat.chunk'
  | 'chat.complete'
  | 'chat.stop'
  | 'tool.started'
  | 'tool.completed'
  | 'tool.confirm'
  | 'agent.check_in'
  | 'agent.run'
  | 'agent.run_parallel'
  | 'agent.stop'
  | 'swarm.run'
  | 'swarm.stop'
  | 'build.start'
  | 'build.output'
  | 'build.complete'
  | 'build.stop'
  | 'preview.ready'
  | 'preview.content'
  | 'files.updated'
  | 'file.request'
  | 'file.history_request'
  | 'error';

/** Base WebSocket message */
export interface WSMessage<T = unknown> {
  type: WSMessageType;
  payload?: T;
  conversation_id?: string;
}

/** Chat message payload */
export interface ChatMessagePayload {
  content: string;
  conversation_id?: string;
  model?: string;
  provider?: string;
  system_prompt?: string;
  mode?: 'plan' | 'ask-before-edits' | 'edit-automatically';
  enable_thinking?: boolean;
  file_context?: FileContext[];
  mcp_tools?: string[];
}

/** File context for chat messages */
export interface FileContext {
  path: string;
  content: string;
  language?: string;
}

/** Chat chunk payload */
export interface ChatChunkPayload {
  content: string;
  conversation_id: string;
  thinking?: boolean;
}

/** Chat complete payload */
export interface ChatCompletePayload {
  conversation_id: string;
  message_id: string;
  metrics?: MessageMetrics;
}

/** Message metrics */
export interface MessageMetrics {
  input_tokens?: number;
  output_tokens?: number;
  thinking_tokens?: number;
  total_tokens?: number;
  latency_ms?: number;
}

/** Tool started payload */
export interface ToolStartedPayload {
  tool_call_id: string;
  tool_name: string;
  parameters: Record<string, unknown>;
}

/** Tool completed payload */
export interface ToolCompletedPayload {
  tool_call_id: string;
  tool_name: string;
  result: string;
  success: boolean;
}

/** Tool confirm payload */
export interface ToolConfirmPayload {
  tool_call_id: string;
  approved: boolean;
}

/** Error payload */
export interface ErrorPayload {
  message: string;
  code?: string;
}

// ============================================================================
// Type Guards
// ============================================================================

/** Type guard for APIResponse */
export function isAPIError<T>(response: APIResponse<T>): response is APIResponse<T> & { error: string } {
  return typeof response.error === 'string' && response.error.length > 0;
}

/** Type guard for APIResponse success */
export function isAPISuccess<T>(response: APIResponse<T>): response is APIResponse<T> & { data: T } {
  return response.data !== undefined && !response.error;
}

/** Type guard for checking if value is defined */
export function isDefined<T>(value: T | undefined | null): value is T {
  return value !== undefined && value !== null;
}
